apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev  # Make sure this is in the 'dev' namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         # Cluster IP port
      targetPort: 80   # Port the pod listens on
      nodePort: 30001  # Expose the service on this port on the node
  type: NodePort       #
